'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';

const pythonCode = `from pydantic import BaseModel
from typing import Optional

class User(BaseModel):
    id: int
    name: str
    email: str
    is_premium: bool = False
    avatar_url: Optional[str] = None

@app.get("/users/{user_id}")
async def get_user(user_id: int) -> User:
    return users_db[user_id]`;

const typescriptCode = `// Auto-generated by PolyRPC
export interface User {
  id: number;
  name: string;
  email: string;
  is_premium?: boolean;
  avatar_url?: string | null;
}`;

const reactCode = `import { py } from '@/lib/polyrpc';

function UserProfile({ userId }: { userId: number }) {
  // Full type inference from Python!
  const { data, isLoading } = py.users.get_user.useQuery({ 
    user_id: userId 
  });

  if (isLoading) return <div>Loading...</div>;

  return (
    <div>
      <h1>{data.name}</h1>
      <p>{data.email}</p>
      {data.is_premium && <span>⭐ Premium</span>}
    </div>
  );
}`;

export function CodePreview() {
  const [activeTab, setActiveTab] = useState<'python' | 'typescript' | 'react'>('python');

  const tabs = [
    { id: 'python', label: 'Python', file: 'models.py' },
    { id: 'typescript', label: 'TypeScript', file: 'polyrpc.d.ts' },
    { id: 'react', label: 'React', file: 'UserProfile.tsx' },
  ] as const;

  const code = {
    python: pythonCode,
    typescript: typescriptCode,
    react: reactCode,
  };

  return (
    <section className="py-16 sm:py-20 lg:py-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-8 sm:mb-12"
        >
          <h2 className="text-2xl sm:text-3xl font-bold lg:text-4xl">
            See the <span className="gradient-text">Magic</span> in Action
          </h2>
          <p className="mt-3 sm:mt-4 text-base sm:text-lg text-zinc-400 max-w-2xl mx-auto px-4">
            Write Python, get TypeScript. No manual work required.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mx-auto max-w-4xl"
        >
          <div className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-hidden shadow-2xl">
            {/* Tab bar */}
            <div className="flex border-b border-zinc-800">
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex-1 px-2 sm:px-4 py-2.5 sm:py-3 text-xs sm:text-sm font-medium transition-colors ${
                    activeTab === tab.id
                      ? 'bg-zinc-800 text-white border-b-2 border-blue-500'
                      : 'text-zinc-400 hover:text-white hover:bg-zinc-800/50'
                  }`}
                >
                  <span className="hidden sm:inline">{tab.label} - </span>
                  <span className="text-zinc-500 truncate">{tab.file}</span>
                </button>
              ))}
            </div>

            {/* Code content */}
            <div className="p-3 sm:p-4 overflow-x-auto">
              <pre className="text-xs sm:text-sm font-mono whitespace-pre">
                <code className={activeTab === 'python' ? 'text-blue-300' : activeTab === 'typescript' ? 'text-green-300' : 'text-purple-300'}>
                  {code[activeTab]}
                </code>
              </pre>
            </div>

            {/* Arrow indicator */}
            {activeTab === 'python' && (
              <div className="border-t border-zinc-800 px-3 sm:px-4 py-2.5 sm:py-3 bg-zinc-800/50 flex flex-wrap items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm">
                <span className="text-zinc-400">Save file</span>
                <span className="text-yellow-400">→</span>
                <span className="text-zinc-400">PolyRPC parses in</span>
                <span className="text-green-400 font-mono">&lt;50ms</span>
                <span className="text-yellow-400">→</span>
                <span className="text-zinc-400">Types ready!</span>
              </div>
            )}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
